# Generated by Django 4.1.7 on 2023-04-26 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0002_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vin_number',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 26, 19, 53, 36, 69414)),
        ),
    ]
