# Generated by Django 4.1.7 on 2023-05-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0006_rename_total_price_order_price_remove_order_car_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Services', 'verbose_name_plural': 'Services'},
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='car_id',
            new_name='car_model_id',
        ),
        migrations.RenameField(
            model_name='serviceprice',
            old_name='id',
            new_name='service_price_id',
        ),
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ImageField(null=True, upload_to='car_photos', verbose_name='Photo'),
        ),
    ]
